spring:
  application:
    name: agrum

  datasource:
      url: jdbc:postgresql://localhost:5432/agrum_dev
      username: postgres
      password:
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # Use 'update' for development so it builds the tables for you.
      # Switch to 'validate' in production using Flyway or Liquibase.
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970" # Must be at least 256 bits for HMAC-SHA
  expiration: 86400000 # 24 hours in milliseconds